<<<<<<< HEAD
app = 'evict-my-tenant-alabama-fly'
primary_region = 'iad'
=======
# fly.toml app configuration file generated for beamns-nick-web-app on 2026-01-20T18:48:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'beamns-nick-web-app'
primary_region = 'ams'
>>>>>>> 6c6b8e28a4f84d00b21ab6c2131d2255a0c54c65

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
<<<<<<< HEAD
  cpus = 1
=======
  cpus = 1
  memory_mb = 256
>>>>>>> 6c6b8e28a4f84d00b21ab6c2131d2255a0c54c65
